### ISSUE TITLE
What is the license? 

### ISSUE THREAD

**Issue by ferventcoder** [secana/PeNet#1]
What license model does this code follow?

**Comment by secana** [comment]
Hi ferventcoder, I never thought about any license. This code is my free time project. If you want to use it, please do so. I don't care if you use it privately or in a commercial application. 

It just would be nice if you find any bugs or write some new features to merge the code into the project. 
I hope I could help you :)

**Comment by ferventcoder** [comment]
@secana sorry to further bother you about this, unfortunately that may not be enough to satisfy legal concerns. If I may suggest a license of Apache 2 or MIT. If you want, I can even provide a pull request to accommodate  this change.  Both licenses also offer you and any contributors protections from legal issues as well - https://github.com/chocolatey/choco/blob/aed7282a60d9b6d162232bb1ed1a4ef48381f328/LICENSE#L153-L163.

**Comment by secana** [comment]
You don't bother me at all. I compared both licenses and decided I'll use the Apache 2 licence from now on. I added the license header to all source files and added a remark on the read me page. 
I'll update the Nuget package on Monday.

**Comment by ferventcoder** [comment]
Awesome, thanks!
