### ISSUE TITLE
.NET TypeRef hash

### ISSUE THREAD

**Issue by jdu2600** [secana/PeNet#100]
It would be useful to have a .NET TypeRef hash - i.e. the .NET equivalent of the ImpHash

I'm not sure if there is an industry standard though?

I've found two implementations (and it looks like the Avast one is more considered/robust ) - 
Avast's decompiler implements a TypeRef hash - https://github.com/avast/retdec/commit/88df33d38e45c999af56d65ef8dc605b76682495
ClrGuard implements a (different) TypeRef hash - https://github.com/endgameinc/ClrGuard/blob/master/ClrGuard/PEMeta.cpp

**Comment by secana** [comment]
I've though about the idea too, but didn't find the implementations you found. I'll have a closer look at the TypeRef hashes. Would be great for malware analysis to have those.

**Comment by secana** [comment]
Started to research if there are any "industry standard" implementations for a TypeRef hash to implement. Waiting for responses...

**Comment by secana** [comment]
Experiment with a TypeRefHash has started, if the results are good, I'll add the code to PeNet.

**Comment by secana** [comment]
First implementation released in PeNet 2.4.0-alpha1

**Comment by secana** [comment]
- [ ] Next: Add documentation article

**Comment by jdu2600** [comment]
Awesome. :-)

Keen to see what you came up with. It looks like you intend to blog about it?

Next to get it added to VirusTotal. :-p

**Comment by secana** [comment]
Blog post is 99% finished. Just need to get it through our PR team. I hope that VT adapts the hash, too. After the blog, I will have a look at the most popular Python PE library and try to implement the TypeRefHash there too, as I guess that would help adoption a lot.

**Comment by secana** [comment]
Blog post is public: https://www.gdatasoftware.com/blog/2020/06/36164-introducing-the-typerefhash-trh
