### ISSUE TITLE
Support streams

### ISSUE THREAD

**Issue by henke37** [secana/PeNet#104]
Things can get awkward with container format and such, so you sometimes only get a Stream to work with.

While it would be possible to "merely" read in all of the stream into a buffer, it's not a good option for big files. Ideally the stream would be seeked to the relevant parts and only relevant data would be read in. Not all streams are seekable, but most are.

**Comment by secana** [comment]
Hi @henke37, do you want something like this `new PeFile(FileStream stream)` or do I misunderstand your request?

**Comment by henke37** [comment]
That is the minimum yes, but as I am suggesting in the prose is that it is efficient too. Don't just blindly copy the entire stream into a `byte[]` and call it a day, that is wasteful. Instead, only read the data that is needed. Personally I tend to use a `SubStream` class a lot in my parsing code.

**Comment by henke37** [comment]
Also, use plain `Stream` instead of `FileStream` in the constructor, not all streams are files. But feel free to use the `as` operator to upcast the given `Stream` to `FileStream` when possible.

**Comment by feliwir** [comment]
I just encountered this issue aswell. Would be great if there was a Stream constructor, so i don't have to load my entire PeFile into Memory :)

**Comment by secana** [comment]
Next: Write unit test for `StreamFile`
