### ISSUE TITLE
Wrong IsExe result for PeNet.dll

### ISSUE THREAD

**Issue by fandrei** [secana/PeNet#128]
IsExe returns true for PeNet.dll v2.0 - should be false instead

**Comment by secana** [comment]
Hi @fandrei, the "IsExe" is right in this case, as the dll is also an executable. The flag is based on the IMAGE_FILE_EXECUTABLE_IMAGE flag. This is a bit strange but that's how Windows works. The "Exe" flag does not tell if the the file is an "*.exe* or an "*.dll* but if it's an executable image, which a dll usually is. So if you want to know if something is an "*.exe", you need to check if the executable flag is true but the dll flag is false. From the MS documentation: "Image only. This indicates that the image file is valid and can be run. If this flag is not set, it indicates a linker error."
I tried to be close to the Windows behavior here, even it it may not be the most user friendly approach...
