### ISSUE TITLE
Strip off one of sections

### ISSUE THREAD

**Issue by fandrei** [secana/PeNet#129]
Is it possible to remove one on file's sections (particularly .rsrc) and save the modified file?

**Comment by secana** [comment]
Good question. I've tried it out and was able to remove the rsrc section from calc.exe while keeping the binary executable.

I've published a new version (2.1.0-alpha1) which now has the member `PeFile.RemoveSection("sectionName")` which removes a section from the PE file. Example code:

```csharp
using PeNet;
using System.IO;

namespace StripSection
{
    class Program
    {
        static void Main(string[] args)
        {
            using var peFile = new PeFile("calc.exe");
    
            // Remove rsrc from section headers
            peFile.RemoveSection(".rsrc", false);

            // Save the changed binary to disk
            File.WriteAllBytes("calc-rsrc.exe", peFile.RawFile.ToArray());
        }
    }
}
```
Feedback is welcome, as I suspect that I did not get it right for every case on the first try. The new version should be available on nuget.org in a few minutes.

**Comment by fandrei** [comment]
@secana it seems that it only removes the section header but keeps the section's content; I wonder if it's possible to remove the section body altogether?

**Comment by secana** [comment]
@fandrei actually it should remove the content per default. Is the binary you work on confidential or could you share it? If so, I can have a look at it again tomorrow.

**Comment by secana** [comment]
Ah sorry, the code example was wrong. The flag disables the strip of the content.

```csharp
using PeNet;
using System.IO;

namespace StripSection
{
    class Program
    {
        static void Main(string[] args)
        {
            using var peFile = new PeFile("calc.exe");
    
            // Remove rsrc from section headers
            peFile.RemoveSection(".rsrc");

            // Save the changed binary to disk
            File.WriteAllBytes("calc-rsrc.exe", peFile.RawFile.ToArray());
        }
    }
}
```

That should work.

**Comment by fandrei** [comment]
@secana this works, thanks.
