### ISSUE TITLE
Quick quesion / possible issue

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#13]
The IsExe attribute ALWAYS returns True for .exe AND .dll files...

While the IsDll attribute returns True only for .dll files. (So this makes sense)

Is the IsExe attribute supposed to return True for ALL .dll files?

Thank you!

**Comment by secana** [comment]
Hi,

I stumbled at that too, when I implemented the parsing of the flags. The behavior you see is correct. The "IsExe" does not mean that the binary before you is an application with an entry point. It means that the binary is executable, as in "contains executable code". Every dll contains executable code and can be executed, thus every dll has the IsExe flag set. It's a pretty confusing flag and I have no idea why Microsoft did it that way, but we have to deal with it. I hope I could answer your question. 

Regards, secana!

**Comment by heywannalaugh** [comment]
Cool, thank you, that is what I was thinking!  Have a great weekend!
