### ISSUE TITLE
How to get TLS Directory RVA

### ISSUE THREAD

**Issue by es3n1n** [secana/PeNet#138]
How i can get TLS Directory RVA which is stored in NtHeaders->OptionalHeader
![image](https://user-images.githubusercontent.com/40367813/80753611-d7e32c00-8b2d-11ea-865e-c70f9d28a06e.png)

**Comment by secana** [comment]
```csharp
var peFile = new PeFile(@"pe.exe");
var tlsDirectoryRva = peFile.ImageNtHeaders.OptionalHeader.DataDirectory[(int) DataDirectoryType.TLS].VirtualAddress;
```
