### ISSUE TITLE
Some Windows files that crash PeNet

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#14]
Hey, sorry to keep bugging you, but here are some Windows files that crash PeNet... they are all standard Microsoft Windows files.

www.desktopfolders.com/Issues.zip

Thank you!

**Comment by secana** [comment]
Hi, these are really strange files. They start like an PE file (DOS Header etc.) but the rest seems to be something else. I'll have a closer look at this issue. Other PE parser tell me that they are no PE file. As a quick fix, I'll do the same, such that PEditor doesn't crash any more.
