### ISSUE TITLE
Error in adding package

### ISSUE THREAD

**Issue by eshagalawatta95** [secana/PeNet#144]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'PeNet 2.2.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

I can't install ur package using nuget.Please conside this issue.

**Comment by secana** [comment]
Hi  @eshagalawatta95, PeNet does not support the old Framework 4.0 anymore. You need at least netstandard2.1 to run it.
