### ISSUE TITLE
How to add a new import to a PE file?

### ISSUE THREAD

**Issue by patrickpissurno** [secana/PeNet#147]
Hello,

Thanks for the library. I took a look at both the docs, the issues and the source code, but couldn't find something similar to what I need to do: programatically add a new import to a PE file.

To read what are the current imports I use `PeFile.ImportedFunctions`, but I noticed it is read only. Any tips on how to achieve that?

My goal is to write an auto patcher that will be able to fetch a DLL from the internet and then patch it to load a custom DLL of mine. I'm able to do that manually using some software I found online called LordPE, but I need to do that programatically. Sadly there's no source code available for it.

I'm also having a tough time grasping how to implement that from scratch myself. The general idea seems to be:
- Parse the PE
- Find the offset where the Import section starts
- Add a new import
- Update the offset
- Probably something more that I might be missing

Then I found out about PeNet and think it might be able to really help me out.

Thanks!

**Comment by secana** [comment]
Hi @patrickpissurno, currently it's not possible to add an import but I'll look into that in the next few days. I guess it should be possible without to many hassles.

**Comment by patrickpissurno** [comment]
I'd really appreciate that! Take your time. Thanks!

**Comment by secana** [comment]
Hi @patrickpissurno I just published `PeNet 2.3.0-alpha1` with the possibility to add imports. I'm pretty sure I broke something, but a new import is available in the import table afterwards. I'll try to debug the issues as soon as I've a bit more time. 

If you want to give the alpha a try:

```charp
var peFile = new PeFile(@"Binaries/add-import.exe");
var ai = new AdditionalImport("GDI32.dll", new List<string> { "StartPage" });
peFile.AddImports(new List<AdditionalImport> {ai});
```

**Comment by secana** [comment]
I guess I fixed the error. I'm able to add multiple new imports to calc.exe without breaking it. `PeNet 2.3.0-alpha2`. @patrickpissurno can you give it a try?

**Comment by patrickpissurno** [comment]
Thank you so much! I'll give it a try right now and reply with the results.

**Comment by patrickpissurno** [comment]
I tested three different scenarios and all of them worked flawlessly. You did an amazing job. As far as I'm aware of (and I searched quite a lot) this is the first library to implement this feature programmatically.

What I tested:
- modifying a 32bit exe to load a 32bit dll
- modifying a 32bit dll to load another 32bit dll
- modifying a 64bit dll to load another 64bit dll

All of them work.

Thank you.

<hr>

For future readers, as the time of writing this, this feature is only available as a prerelease. So when getting it from NuGet, don't forget to check the "Include prerelease" box.

For the DLL to be loaded correctly, it seems that we need to import something that is actually exported by the DLL. Even if we just want to use the `DllMain`.

Here's a fully working sample.

`my_sample_dll.cpp` (DLL to be imported)
```c++
#include <windows.h>

#define PUBLIC_API __declspec(dllexport)
extern "C" PUBLIC_API void custom_stub() { }

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
{
    MessageBox(0, TEXT("Loaded successfully"), TEXT("Success"), MB_ICONINFORMATION);
    return TRUE;
}
```

`program.cs` (patcher application)
```c#
using PeNet.Header.Pe;
using System;
using System.Collections.Generic;
using System.IO;

 static class Program
{
    static void Main()
    {
        //load the target dll with PeNet
        var dll = new PeNet.PeFile("target.dll");

        //add our new import to the dll (in memory)
        var ai = new AdditionalImport("my_sample_dll.dll", new List<string> { "custom_stub" });
        dll.AddImports(new List<AdditionalImport> { ai });

        //write changes to disk, the original target.dll file is not modified by this sample
        File.WriteAllBytes("target_modded.dll", dll.RawFile.ToArray());

        Console.WriteLine("Patched successfully");
    }
}
```

By running the above example the `target.dll` file will be patched to load `my_sample_dll.dll`. The patched `target.dll` will be saved as `target_modded.dll`.

Then you can just replace the original `target.dll` file in the program's directory with the patched one, and don't forget to place `my_sample_dll.dll` in that same directory. Fire up the program and you should see the "Loaded successfully" message.

**Comment by secana** [comment]
Happy to hear that it works. I'll keep the alpha out for a few more day in the case that you stumble upon a bug. If not I'll merge it into master and release 2.3.0.

**Comment by secana** [comment]
Documentation to add imports: http://secana.github.io/PeNet/articles/imports.html
