### ISSUE TITLE
A few small specific issues

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#15]
Hey, here are a few more samples that reproduce bugs… they are all malware, so the zipped file is password protected with the password “infected”.

The Resource.ResourceDirectory.Manifest Crash.exe will crash PeNet when you navigate to the Resource tab, then expand Resource Directory, and then expand Manifest.

The other two files have invalid values under the Sections tab… I believe because they contain embedded files.

http://www.desktopfolders.com/Malware2.zip

Thank you!

**Comment by secana** [comment]
Hi, I looked into the issues and (hopefully) fixed them. I'll do a bit more work on PeNet in the next days so that the fixes should be in the next release. 

Thx again very much!

**Comment by heywannalaugh** [comment]
Sounds great... I tested tons of files and I am pretty sure that there will not be anymore issues, thank you as well!
