### ISSUE TITLE
Resource names not parsed properly

### ISSUE THREAD

**Issue by pfamircea** [secana/PeNet#151]
When you have a bunch of resources, also nested and such, the names are not parsed properly. (since they are parsed till the first null char, while they appear as an array of [length][name].

Got a branch prepared. Can someone provide push access so I can get a branch up?

Thanks.

**Comment by secana** [comment]
Hi, you fix is really appreciated. Could you do me favor and create a pull request? That makes it easier to review and the CI pipeline with tests runs.

**Comment by pfamircea** [comment]
I tried that already yesterday and now again, but I still get 
`remote: Permission to secana/PeNet.git denied to pfamircea.
fatal: unable to access 'https://github.com/secana/PeNet.git/': The requested URL returned error: 403
`

**Comment by secana** [comment]
You need to fork the repository and than create a pull request. 

- [Github Fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
- [Github Pull](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by pfamircea** [comment]
Hopefully this cuts it: https://github.com/secana/PeNet/pull/152
