### ISSUE TITLE
Make ComputeAuthenticodeHashFromPeFile public

### ISSUE THREAD

**Issue by sgso** [secana/PeNet#186]
Hello,

first thing: Thank you for this great library! I'm using PeNet to verify files against their Authenticode signatures and now want to extend this to security catalog signed files as well. I use this to cull irrelevant files from forensic images (LE).

My request: It would be extremely handy if it was possible to calculate PE hashes (parameterized by hash algorithm) with PeNet. Since I'm trying to stay platform independent `ImageGetDigestStream` is not an option and I'd like to avoid maintaining a fork for such a minuscule change.

I hope you'll consider this.

Thank you

**Comment by secana** [comment]
Hi @sgso,

happy to hear that PeNet is of use to you. I'm not sure, if I understand what you need correctly.

Currently PeNet supports a few hashes out of the box (MD5, SHA1, SHA256, ImpHash, TypeRefHash). For more information have a look at:
File hashes: http://secana.github.io/PeNet/articles/filehash.html
ImpHash: http://secana.github.io/PeNet/articles/imphash.html
TypeRefHash: http://secana.github.io/PeNet/articles/typerefhash.html

If you need access to the file as a stream to compute your own hashes you can use http://secana.github.io/PeNet/articles/parseroptions.html#open-a-pe-file and access the underlying file with `peFile.RawFile` which gives you different methods to work with the PE file directly http://secana.github.io/PeNet/api/PeNet.FileParser.IRawFile.html.

Is that something that helps? If not, could you elaborate a bit more what you need? Btw. if you have any code that does what you want, a PR is very welcome.

**Comment by sgso** [comment]
@secana I'm interested in the "PE hash"/ "Authenticode Hash" calculated in
 `private IEnumerable<byte>? ComputeAuthenticodeHashFromPeFile(HashAlgorithm hash)` in the file `/Header/Authenticode/AuthenticodeInfo.cs`.

**Comment by secana** [comment]
Alright, I released a new prerelease version "2.6.1-pre1" where the method is public. It should be on NuGet in a few minutes, as soon as the Nuget index found it. 
If that works for you, please notify me shortly and I'll merge the changes to master an release "2.6.1".

**Comment by sgso** [comment]
Perfect. Thank you very much.
