### ISSUE TITLE
Support for .NET Framework 4.8

### ISSUE THREAD

**Issue by pavledev** [secana/PeNet#192]
Can you please add support for .NET Framework 4.8?

**Comment by IllidanS4** [comment]
I'd also welcome support for .NET Standard 2.0; that would solve the issue.

**Comment by Xkein** [comment]
> I'm investigating if that is possible with System.Memory but so far it doesn't seem to work. PeNet is heavily performance optimized and uses a lot of the newest runtime and language features.
> 
> I'll keep the issue open, in the case I make some progress on a back-port.

Hey, i have try some change and seems it work fine under net48. please see my [commit](https://github.com/Xkein/PeNet/commit/1d756ef5a2764c4a81ed838b8b8e5ee9e184bc9a).
By the way, i wonder what problem did you meet when you converting into net48?

Thank you for making the PeNet!

**Comment by secana** [comment]
Hi @Xkein you commit looks very promising. Could you create a PR? If all tests succeed, I'll publish a new version with support for .NET 4.8

**Comment by Xkein** [comment]
get it.

**Comment by secana** [comment]
@Xkein thx for the PR. New version (2.7.0) with your additions it out.
