### ISSUE TITLE
COM TypeLib ID (TLID) parsing broken?

### ISSUE THREAD

**Issue by evandrix** [secana/PeNet#202]
https://github.com/secana/PeNet/blob/1172a5fd9164b5ae9d4c8fb06219b78b1aff8057/src/PeNet/Header/Net/NetGuids.cs#L58-L136
- running the referenced original code https://github.com/cylance/GetNETGUIDs/blob/master/getnetguids.py,
- and verifying with VirusTotal (VT) https://www.virustotal.com/gui/file/af7ce8dcb16b6344de9856e96ce83b642bcc5ee1c0d29e3a0dcd96e67c65a085/details,
- the COM TypeLib ID should be `35078dfe-0ce9-4a46-b6be-790d443ff486`,
- but it's returning nothing null for sample SHA256:`af7ce8dcb16b6344de9856e96ce83b642bcc5ee1c0d29e3a0dcd96e67c65a085`?

**Comment by secana** [comment]
@evandrix thx for reporting the bug. Should be fixed in PeNet 2.6.4, which is available in a few minutes on Nuget
