### ISSUE TITLE
ArgumentOutOfRangeException thrown during computation of TypeRefHash

### ISSUE THREAD

**Issue by FlorianHockmann** [secana/PeNet#221]
We frequently see this exception in our processing. I don't know yet whether this is caused by a bug in PeNet or whether the .NET header is malformed.

Full stack trace:
```c#
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at PeNet.Header.Net.MetaDataTablesHdr.ParseTableDefinitions()
   at PeNet.Header.Net.MetaDataTablesHdr.get_TableDefinitions()
   at PeNet.Header.Net.MetaDataTablesHdr.ParseTable[T](MetadataToken token)
   at PeNet.Header.Net.MetaDataTablesHdr.ParseMetaDataTables()
   at PeNet.Header.Net.TypeRefHash.ComputeHash()
   at PeNet.PeFile.get_TypeRefHash()
```

This malware sample for example leads to the exception: https://www.virustotal.com/gui/file/f88e743fdd410a89b7084076883164120e3abe7f8f08ad65bb0fec05b392d3b1/

**Comment by FlorianHockmann** [comment]
I just looked a bit deeper into this and found the place where the exception is thrown. It's in the beginning of the [`ParseTableDefinitions` method](https://github.com/secana/PeNet/blob/bcd781c43a061a566eb98ec8cdb32e71732d8cda/src/PeNet/Header/Net/MetaDataTablesHdr.cs#L182):

```c#
var tables = new MetaDataTableInfo[64];

var startOfTableDefinitions = Offset + 24;
var names = ResolveMaskValid(MaskValid);

// Set number of rows per table
var cnt = 0;
for (var i = 0; i < tables.Length; ++i)
{
    if (((ulong)MaskValid & (1UL << i)) != 0)
    {
        tables[i].RowCount = PeFile.ReadUInt(startOfTableDefinitions + (uint)cnt * 4);
        tables[i].Name = names[cnt];
        cnt++;
    }
}
```

`ResolveMaskValid` returns a list of 27 entries, but `tables` has 64 entries. This leads to the `ArgumentOutOfRangeException` for `cnt = 27` when `names[cnt]` is accessed for this binary.

**Comment by secana** [comment]
I've looked into the sample and it seems to be crypted somehow. The data in the metadata tables is broken and cannot be recovered. None the less, PeNet should't just crash on that, but instead fail to parse the broken parts. I'll see what I can do about that.

**Comment by secana** [comment]
Mitigated in PeNet 2.9.2

If  a broken table is encountered, the TRH is "null" instead of an exception.

**Comment by Washi1337** [comment]
The file is not broken, but (ab)uses a feature that the CLR implements but is not specified in ECMA-335. 

The storage header can contain additional extra data right after the row counts of the tables. This is a 32-bit integer field that is only present when an undocumented flag (`0x40`) is set in the `Flags` field (also known as `HeapOffsetSizes`) of the tables stream header (`#~`, `#-` or `#Schema`).

If you don't read these extra bytes, the metadata tables are not parsed properly, resulting in string offsets being read incorrectly and thus names not being read properly.

References:
- https://github.com/dotnet/runtime/blob/main/src/coreclr/md/inc/stgtiggerstorage.h
- https://github.com/dotnet/runtime/blob/ce2165d8084cca98b95f5d8ff9386759bfd8c722/src/coreclr/md/enc/stgtiggerstorage.cpp#L858
- https://github.com/dotnet/runtime/blob/ce2165d8084cca98b95f5d8ff9386759bfd8c722/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Internal/MetadataFlags.cs#L145

**Comment by secana** [comment]
Hi @Washi1337,

would you be interested in creating a PR?

**Comment by Washi1337** [comment]
Sure I can have a look at it when I get the time somewhere next week. I am not too familiar yet with the internals of this library yet, so will have to read up on that first.
