### ISSUE TITLE
ImageOptionalHeader.Subsystem isn't settable

### ISSUE THREAD

**Issue by MrJul** [secana/PeNet#224]
When upgrading from PeNet 1.6.1 to 2.9.2, I was blocked due to the lack of a setter for `ImageOptionalHeader.Subsystem`, which existed before. Since all other properties are settable, I assume it's simply an oversight, and can open a PR if needed.

Relevant code: https://github.com/secana/PeNet/blob/efd720667b4bdf0e10fe9c2414fe54da5815c760/src/PeNet/Header/Pe/ImageOptionalHeader.cs#L261:263

**Comment by secana** [comment]
Hi @MrJul,

a PR would be appreciated!

**Comment by MrJul** [comment]
Done, PR #225 open :)
