### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Lifka** [secana/PeNet#227]
Hi, 

I was trying PeNet to analyze samples and it's awesome. But I think I found a condition that makes it crash, if you want to take a look, you can try using this sample: [02fc683cb53ab54ddd1b25a28875cccccc2c5c20419a173a46e7b908706ce49546](https://www.virustotal.com/gui/file/02fc683cb53ab54ddd1b25a28875cccc2c5c20419a173a46e7b908706ce49546/details)

The library enters an infinite loop and saturates the machine's memory until it crashes.

**Comment by secana** [comment]
fixed in 2.9.5
