### ISSUE TITLE
not usable in .Net Framework

### ISSUE THREAD

**Issue by ticktickMOF** [secana/PeNet#23]
Since the conversion to .NET Core and .NET Standard NuGet in VS 2015 doesn't allow PeNet to be referenced by .NET Framework projects.

> Could not install package 'PeNet 0.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by secana** [comment]
Hi @ticktickMOF I just tried it our and I can install PeNet into an .Net 4.6.1 project. Do you have the .Net Standard 2.0 SDK installed? Regarding this page you need it to use an .Net Standard 2.0 package with an 4.6.1 project. https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I'll check if I can build a package that contains an 4.6.1 assembly anyways. Regards, secana.

**Comment by secana** [comment]
I published a new version 0.5.1 which targets .Net 4.6.1 directly. I hope that fixes your issue.

**Comment by stonedreamforest** [comment]
@secana  i need install it in my wpf project, but i get  a error:
```

Attempting to gather dependency information for package 'PeNet.2.4.0' with respect to project 'PHAmazing', targeting '.NETFramework,Version=v4.7'
Gathering dependency information took 49 ms
Attempting to resolve dependencies for package 'PeNet.2.4.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'PeNet.2.4.0'
Resolved actions to install package 'PeNet.2.4.0'
Install failed. Rolling back...
Executing nuget actions took 567 ms
Could not install package 'PeNet 2.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:00.9008100
```
do I need to reopen a new issue?

**Comment by ZonderP** [comment]
> @secana i need install it in my wpf project, but i get a error:
> 
> ```
> 
> Attempting to gather dependency information for package 'PeNet.2.4.0' with respect to project 'PHAmazing', targeting '.NETFramework,Version=v4.7'
> Gathering dependency information took 49 ms
> Attempting to resolve dependencies for package 'PeNet.2.4.0' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'PeNet.2.4.0'
> Resolved actions to install package 'PeNet.2.4.0'
> Install failed. Rolling back...
> Executing nuget actions took 567 ms
> Could not install package 'PeNet 2.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> Time Elapsed: 00:00:00.9008100
> ```
> 
> do I need to reopen a new issue?
> 
> i install 1.6.1 resolve this problem

All versions >= 2 cannot anymore be used in projects targeting .Net Framework.
You either need to rewrite your code to target .Net Core or stick to an older version like you obviously already did.
Find why this is so here:
https://github.com/secana/PeNet/issues/113
