### ISSUE TITLE
Memory exhaustion issue

### ISSUE THREAD

**Issue by SteAmeR** [secana/PeNet#235]
Hi,

Today I came across a fatal issue on PeNet when I analyzed a malware sample that I found on malwarebazaar. The sample size is 554 kb and it's type is a xll file (a excel plugin of some kind) 
Sample link: https://bazaar.abuse.ch/sample/b9eeeea558d05af8a3c03070a5960a95f5e9c5d7671d2e15e917a3d911cb846b/

The physical memory consumption reaches the very critical range and is exhausted when I want to analyze this sample in my project that is dependent on penet. 

![penet-exhausting](https://user-images.githubusercontent.com/399791/165187026-9d1a3371-4e74-4859-b699-b26bb47c901f.PNG)

Can a fix be released for this issue?

**Comment by rngcntr** [comment]
I noticed similar behavior recently and prepared a potential fix together with @secana today. I'll link the PR here once it is ready for review.

**Comment by secana** [comment]
@rngcntr @SteAmeR can you check if the problem still exists with the version `2.9.8-pre1`? Should be available on NuGet in a few minutes.

**Comment by SteAmeR** [comment]
> @rngcntr @SteAmeR can you check if the problem still exists with the version `2.9.8-pre1`? Should be available on NuGet in a few minutes.

The fix is tested and validated. Thx

**Comment by rngcntr** [comment]
Confirmed, `v2.9.8-pre1` reduced both compute and memory resources by two orders of magnitude for certain samples.
