### ISSUE TITLE
Possibility to merge .dll into .exe file ?

### ISSUE THREAD

**Issue by tapika** [secana/PeNet#243]
PeNet in theory offers mechanism of adding and maybe even manipulating existing sections.

How complex it would be to merge .dll into .exe file directly ?

What I have checked .dll and .exe typically contains 
```
.text
.rdata
.pdata
.idata
.00cfg
.rsrc
.reloc
```

named section. How complex would it be to merge all sections using some logic using PeNet ?

If someone has done this already, maybe could give a description on how to do it or ideate as far as it's possible ?

**Comment by secana** [comment]
That would mean, that the work that a linker usually does needs do be implemented into PeNet. While I like the idea, I guess that's too much work for an open source project without any company behind it.

**Comment by tapika** [comment]
This does not seems to be reasonable simple as well, added brief comments into here:

https://github.com/tapika/test_native_dll_loading/discussions/2#discussioncomment-2800172
