### ISSUE TITLE
Add example code which can extract multiple icons as one .ico file

### ISSUE THREAD

**Issue by tapika** [secana/PeNet#258]
See following answer: https://stackoverflow.com/a/74411477/2338477

Would it be possible to code example which would replace `IconLib.Unofficial` nuget package use ?

**Comment by tapika** [comment]
Hmm... There exists also following [article](https://vec3.ca/extracting-icons-from-pe-files) if it can be used ?

**Comment by rngcntr** [comment]
Hi @tapika!

I have discussed the possibility to export multiple icons as single .ico files with other contributors. Our goal was to align this implementation with the behavior of other popular PE file utilities in terms of exporting the same formats etc.
IIRC, neither CFF Explorer nor Resource Hacker pack multiple icons into one file so we decided not to do so either. Anybody who explicitly needs to have the icons packed in a single file, can still use the icons extracted by PeNet and handle the rest themselves. However, If you would like to see this feature and think others might need it as well, you are free to open a PR of course.

**Comment by tapika** [comment]
I think this PR already opened, unless you close it.

Florian Grieskamp was also asking on .exe samples which can be used for testing - you can use these readytorun executable file for example: https://github.com/tapika/swupd/releases

Btw - I have tried to locate software I have used once upon a time to check multiple icons - and there exists
[greenfish icon editor pro 4.0](http://greenfishsoftware.org/gfie.php), which is freeware and can be used for testing.

And [shimgen](https://github.com/tapika/swupd/tree/develop/src/shimgen) from here can be even used for roundtrip testing - so you extract icon, provide it to .net compiler, and get it back to another executable.

`shimgen.exe --path="C:\Users\user\Downloads\choco.exe" --output=shortcut.exe  --iconpath="C:\Users\user\Downloads\choco.exe" --debug`
