### ISSUE TITLE
The AuthenticodeInfo.IsAuthenticodeValid property is misleading

### ISSUE THREAD

**Issue by softworkz** [secana/PeNet#262]
First of all, thanks a lot for creating and sharing this great library!  
In order to do cross-platform Authenticode validation, I had already been on a path going with `System.Reflection.PortableExecutable`  when I saw your message in an issue over at ms/dotnet regarding non-Windows issues. There's a lot of valuable knowledge in your code, even though - this time - it's been just the Authenticode bits that I gladly adopted,  
Yet I felt I should at least share some experience in return.

Before I get to the primary subject, some other observations:

### Performance when Accessing Authenticode information

At some point I wanted to compare the performance and memory usage between `BufferFile`, `StreamFile` and `MMFile`.

Just a note on MMIO, which I discarded early: From my (earlier) experience (which `MMFile` performance confirmed again), MMIO can provide some advantage for (non-shared) file access on Linux, but rarely on Windows. On Windows, you get worse performance than with regular file access most of the time. The typical (and probably only) advantageous use case for MMIO on Windows is shared access to the same file across multiple processes.

So, I'll focus on the comparison of `BufferFile` and `StreamFile` performance for checking Authenticode. I  had created tests which loop through a  a few dozens of files and write a line to the test output for each.  
I was surprised to see that access via `BufferFile` was about 2 times faster than with `StreamFile`. Clearly, this couldn't be right.   
It turned out that the log line itself is the key for the performance difference:

```c#
this.output.WriteLine("{0,-30} IsSigned: {1} HasValidSignature: {2} verified: {3}", name, 
     peFile.IsSigned, peFile.Authenticode?.IsAuthenticodeValid, peFile.Authenticode?.SigningCertificate?.Verify());
```

All three property-get calls..

*   `PeFile.IsSigned`
*   `PeFile.Authenticode?.IsAuthenticodeValid`
*   `PeFile.Authenticode?.SigningCertificate`

are triggering another (new) Authenticode parsing incl. hash and signature calculation for the same file. As the data is completely loaded into memory in case of BufferFile, the second and third parsing, is faster than with file stream access.

Probably it would be a good idea to store the result of the first Authenticode parsing and return it for subsequent accessing of the properties.

### Confusing Property Names and Locations

Same area as above. It took me a while to understand the meaning and relation of some of the properties that are available for Authenticode, namely:

*   `PeFile.Pkcs7`  
    (returns `PeFile.Authenticode?.SigningCertificate`)  
    Before I had looked at the source, I was wondering what this might be and where it would come from. I would have never thought that it would be the Authenticode certificate
*   `PeFile.IsSigned`  
    (returns `PeFile.this.Pkcs7 != null`)  
     equal to `PeFile.Authenticode?.SigningCertificate != null`)  
    IsSigned sounded to me as if it would indicate whether a .net assembly has been signed with a strong-name key
*   `PeFile.HasValidSignature`  
    also wasn't clear
*   PeFile.Authenticode  
    The existence of that property is actually what caused the confusion about the others above, and the fact that it provides the same information but with different naming.

Though, not a big deal once you know it.. :wink: 

### IsAuthenticodeValid Property is Misleading

Finally to the subject. The naming suggests that `IsAuthenticodeValid` would be semantically equal to when a user checks the signature of a binary file in Windows Explorer => File => Properties => Digital Signatures => Details => \[Valid / Invalid\].

But it's not equal, at least for two cases:

#### 1\. IsAuthenticodeValid does not indicate whether the certificate is trusted

`SignedCms.CheckSignature(true)` doesn't do this.   
It is required to call `X509Certificate2.Verify()` for checking certificate trust.

(I can provide a repro scenario for testing)

#### 2\. IsAuthenticodeValid does not verify signing purposes

When you change the allowed purposes of a root certificate and remove the signing purpose, Windows shows the certificate as invalid. None of the methods above checks for this (tested).

The manual change of a CA cert is probably not much of a concern. What would be a concern though, is when somebody could sign a binary with an e-mail or website certificate. I don't have a repro for the latter, though.

Thanks!

**Comment by secana** [comment]
Hi @softworkz thanks for the very valuable feedback. We are currently working on PeNet 3.0.0. As we bump the major version, we can introduce some breaking changes. I'll see how I can incorporate your feedback :)

**Comment by softworkz** [comment]
Great, thanks!
