### ISSUE TITLE
Version and Flags are swapped in UnwindInfo

### ISSUE THREAD

**Issue by gsuberland** [secana/PeNet#267]
Microsoft [documents](https://learn.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-170) the unwind info structure as follows:

> UBYTE: 3 | Version
> 
> UBYTE: 5 | Flags

In packed nomenclature, this means that the _bottom_ 3 bits (LSBs) represent the version, and the _top_ 5 bits (MSBs) are the flags.

However, in the code, this is backwards:

https://github.com/secana/PeNet/blob/57a94989c1855b31a1c2768377e65d10f5d563bc/src/PeNet/Header/Pe/UnwindInfo.cs#L25-L33

i.e. Version is being read from the top 3 bits and Flags is being read from the bottom 5.

This error can be confirmed by the fact that the version field must always be 1, and this is not the case with the code as it is.

I've also confirmed that the current behaviour does not match CFF Explorer's parsing of the UnwindInfo.

**Comment by secana** [comment]
Hi @gsuberland, thanks you for reporting the bug! Would you care to create a PR to fix it? If not, I'll do it, as soon as I've time.
