### ISSUE TITLE
ExportedFunctions is null despite a valid export data directory

### ISSUE THREAD

**Issue by unkusr007** [secana/PeNet#271]
Steps to reproduce:
- Open a notepad
- read notepad process memory and dump `vcruntime140.dll` module
- create a `PeFile` with the module content
- `ExportedFunctions` is null.

**Comment by secana** [comment]
If I understand you correctly, you try to open a dump of a module not a PE file from disk? PeNet does not support PE files from memory, only from disk.

**Comment by unkusr007** [comment]
Ok that's too bad! Thanks.
