### ISSUE TITLE
Add .Net header to PeNet

### ISSUE THREAD

**Issue by secana** [secana/PeNet#28]
Implement the .Net header in PeNet

**Comment by secana** [comment]
Already implemented the Meta Data streams GUID, Blob, String and US
Next big step is the implementation of the Meta Data Tables.

**Comment by secana** [comment]
Implemented the first table "Module" incl. resolving from the .Net heaps.
Next table is AssemblyRef

**Comment by secana** [comment]
The offsets of the different Meta Data Tables are not known before hand. The offset of a table is defined by the length of the previous table.

This means that the tables have to be implemented in the following order:

- [ ] 00 - Module
- [ ] 01 -TypeRef               
- [ ] 02 -TypeDef
- [ ] 04 - Field                   
- [ ] 06 - MethodDef              
- [ ] 08 - Param
- [ ] 09 - InterfaceImpl           
- [ ] 10 - MemberRef              
- [ ] 11 - Constant
- [ ] 12 - CustomAttribute         
- [ ] 13 - FieldMarshal          
- [ ] 14 - DeclSecurity
- [ ] 15 - ClassLayout             
- [ ] 16 - FieldLayout            
- [ ] 17 - StandAloneSig
- [ ] 18 - EventMap                
- [ ] 20 - Event                  
- [ ] 21 - PropertyMap
- [ ] 23 - Property                
- [ ] 24 - MethodSemantics       
- [ ] 25 - MethodImpl
- [ ] 26 - ModuleRef               
- [ ] 27 - TypeSpec               
- [ ] 28 - ImplMap
- [ ] 29 - FieldRVA                
- [ ] 32 - Assembly               
- [ ] 33 - AssemblyProcessor
- [ ] 34 - AssemblyOS              
- [ ] 35 - AssemblyRef            
- [ ] 36 - AssemblyRefProcessor
- [ ] 37 - AssemblyRefOS           
- [ ] 38 - File                   
- [ ] 39 - ExportedType
- [ ] 40 - ManifestResource       
- [ ] 41 - NestedClass            
- [ ] 42 - GenericParam
- [ ] 44 - GenericParamConstraint

**Comment by secana** [comment]
Before the actual tables can be implemented the different indices have to be implemented.

- [ ]  TypeDefOrRef
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by secana** [comment]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by secana** [comment]
- [ ] Fix tests for NetCoreConsole
- [ ] Implement Method parsing based on [Methods](https://www.codeproject.com/Articles/12585/The-NET-File-Format#Methods)

**Comment by nurajbihari** [comment]
Can the resolved names be accessed using PeNet? How can I access the resolved names for the typeref table?

**Comment by secana** [comment]
@nurajbihari sure, have a look at this test for an example: https://github.com/secana/PeNet/blob/05133c9692d20be2f951cf22ba6d951f0bd810f6/test/PeNet.Test/Header/Net/NetCoreConsoleTest.cs#L147
