### ISSUE TITLE
Not detecting import from RPCRT4.dll

### ISSUE THREAD

**Issue by hoglund666** [secana/PeNet#283]
Analyzing dbghelp.dll from Windows 10, DLL version 10.0.19041.867.  One of the imports appears to be UuidCreate from RPCRT4.dll but this isn't being reported as an import by PeNet.  I haven't looked into it in detail, but IDA-Pro detects the import, as does Dependency Walker.  Maybe there is a quirk in the way it's being imported, but PeNet misses it.

**Comment by alexrp** [comment]
Took a quick peek. That function seems to be delay-loaded, which is probably why PeNet doesn't pick it up.

**Comment by secana** [comment]
Yes, delay loaded libraries is not implemented a.t.m. I would accept in PR, if you know how it's done @hoglund666.

**Comment by hoglund666** [comment]
Thanks for looking. Completely understand with the delay load. That would be beyond scope for a static analysis library. I noticed that DLL is loaded in a bunch of processes. I’m curious who loaded it? Was it an OS library?

-G

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
