### ISSUE TITLE
PeFile ignores exported functions without a name

### ISSUE THREAD

**Issue by camerondm9** [secana/PeNet#3]
Some DLLs have functions that are exported by ordinal only. These functions do not have a name at all, so NumberOfNames is not equal to NumberOfFunctions. I have modified PeFile.ParseExportedFunctions, and can confirm that this code works on my test file:

        private PeFile.ExportFunction[] ParseExportedFunctions(byte[] buff, Structures.IMAGE_EXPORT_DIRECTORY ed, Structures.IMAGE_SECTION_HEADER[] sh)
        {
            var expFuncs = new PeFile.ExportFunction[ed.NumberOfFunctions];
            var funcOffsetPointer = Utility.RVAtoFileMapping(ed.AddressOfFunctions, sh);
            var ordOffset = Utility.RVAtoFileMapping(ed.AddressOfNameOrdinals, sh);
            var nameOffsetPointer = Utility.RVAtoFileMapping(ed.AddressOfNames, sh);

            var funcOffset = Utility.BytesToUInt32(buff, funcOffsetPointer);
            
            //Get addresses
            for (uint i = 0; i < expFuncs.Length; i++)
            {
                var ordinal = i + ed.Base;
                var address = Utility.BytesToUInt32(buff, funcOffsetPointer + sizeof(uint) * i);

                expFuncs[i] = new PeFile.ExportFunction(null, address, (ushort)ordinal);
            }

            //Associate names
            for (uint i = 0; i < ed.NumberOfNames; i++)
            {
                var namePtr = Utility.BytesToUInt32(buff, nameOffsetPointer + sizeof(uint) * i);
                var nameAdr = Utility.RVAtoFileMapping(namePtr, sh);
                var name = Utility.GetName(nameAdr, buff);
                var ordinalIndex = (uint)Utility.GetOrdinal(ordOffset + sizeof (ushort)*i, buff);
                
                expFuncs[ordinalIndex] = new PeFile.ExportFunction(name, expFuncs[ordinalIndex].Address, expFuncs[ordinalIndex].Ordinal);
            }

            return expFuncs;
        }

My reference for this modification was http://web.archive.org/web/20160306071658/http://win32assembly.programminghorizon.com/pe-tut7.html

**Comment by secana** [comment]
Hi camerondm9,

your are right, I only parsed functions exported by name, but functions exported by ordinals should be in the list, too. I tested your code an really like it. I've already implemented your changes in the library and I'll publish a new NuGet package on monday. 

Thank you very much for you contribution!
