### ISSUE TITLE
Request for permissions to use and implement PeNet

### ISSUE THREAD

**Issue by creizlein** [secana/PeNet#317]
I have a small C# project that tries to be an Windows Task Manager alternative , which you can check at @sMkTools/sMkTaskManager - https://github.com/sMkTools/sMkTaskManager -  and among the new features I will implement is a PE explorer/inspector for executable files. 

Would like to confirm if it is Ok to use, implement and reference your library from within my application, you may just ignore or close this issue but would like just to say it, hope its ok, let me know if not.

Will be rather easy to use your native C# code rather than writing the whole lot of P/invoke calls to use the Win32 API.

Cheers

**Comment by secana** [comment]
Sure, go ahead. I'm happy whenever PeNet gets used.
