### ISSUE TITLE
How to save file?

### ISSUE THREAD

**Issue by ImmuneLion318** [secana/PeNet#335]
As the title says I'm doing decrypting and stuff using it which involves modifying sections anyways my output code is as follows
```cs
        File.WriteAllBytes("./Dumped.exe", Executable.RawFile.ToArray());
```
idk if this works or not but please tell me cause the output binary appears to be wrong from my decrypting stuff so it could be me outputting it like this or some other issues either way i needa know the proper way to output the file.

**Comment by secana** [comment]
Yes, that is the right way to do it.

What does not work for you?
