### ISSUE TITLE
.Net Framework Request Support 2.0

### ISSUE THREAD

**Issue by tututu-patch** [secana/PeNet#56]
I hope to build the runtime target .Net Framework 2.0 for it.

**Comment by secana** [comment]
Sry, I'm already supporting net40 which is the lowest I'll go with the library. Can you elaborate why you need such on old framework supported?

**Comment by tututu-patch** [comment]
Because .Net 2.0 has good compatibility, Windows XP cannot now install .Net 4.0.

**Comment by secana** [comment]
I'm not sure if that's true. .Net 4.0 can be installed on Windows XP: https://blogs.msdn.microsoft.com/dotnet/p/dotnet4xp/

**Comment by tututu-patch** [comment]
Ok, thank you. I have never known.
