### ISSUE TITLE
What is missing for a 1.x version?

### ISSUE THREAD

**Issue by drauch** [secana/PeNet#67]
What do you think is missing for a 1.0 version step? We'd like to use your library, however our company has a kind of "no beta libraries" policy and we're concerned because of the 0.x version indicator. Would you think that the library can be used to parse the IMAGE_FILE_EXECUTABLE_IMAGE flag or do you think that your library isn't that far and we should consider implementing this ourselves instead?

Best regards,
D.R.

**Comment by secana** [comment]
Hi D.R.,

the library implements the whole PE header and most important parts of the .Net header. What is missing to for the 1.0 (currently working on it) is a better documentation and CI system. The library is used in multiple production projects, so there is no reason to not use it.

Regards,
 Stefan

**Comment by drauch** [comment]
Thank you for your quick reply. If we may, we'd have two more questions:

1) Is your library loading the whole PE file into memory? Is there a way to only load the headers so memory consumption stays low?

2) Have you gotten around to fix the memory leak described in https://github.com/secana/PeNet/issues/16?

Thank you again for your hard work!

Best regards,
D.R.

**Comment by secana** [comment]
Unfortunatly the library loads the whole binary into memory, because I don't know the size of the PE Header before hand. 
If you have very large files, it is reasonable to assume that the Header is in the first 1 MB of the file. In this case you can read only the first MB from disk and hand the small Buffer to PeNet. In this case you won't have to load the whole binary.

The issue #16 was a bit hard to understand. The memory leak was not in the PeNet library which you want to use, but in an GUI Editor I wrote that uses the library. If opened multiple large files after each other, they weren't disposed correctly. Because I don't maintain the GUI Editor anymore (I want to write a cross-plat one), I've closed the issue.

Hope that helps.

Stefan

**Comment by drauch** [comment]
> If you have very large files, it is reasonable to assume that the Header is in the first 1 MB of the file. In this case you can read only the first MB from disk and hand the small Buffer to PeNet. In this case you won't have to load the whole binary.

That should suffice for our needs, thank your for the hint.

> The memory leak was not in the PeNet library which you want to use, but in an GUI Editor

Okay, thanks for the information.

Very mature and useful replies - and quick as well. Thanks for your work!

Best regards,
D.R.

**Comment by drauch** [comment]
Hm, one more thing though. Is there a maximum PE file header size? I realized that when the buffer is too small, PeNet runs into an IndexOutOfRangeException instead of partially building up the model and/or throwing a useful exception.

**Comment by secana** [comment]
Puh, good questions. Not that I know of. But if you could provide me a sample where the case happens, I could improve PeNet to return the header as far as it's possible.

**Comment by drauch** [comment]
var bytes = 495; // 496 works, 495 throws ArgumentNullException, 10 throws IndexOutOfRangeException
    var buf = new byte[bytes];
    var fs = new FileStream("C:\\Users\\<youruser>\\Downloads\\kernel32.dll", FileMode.Open, FileAccess.Read);
    fs.Read(buf, 0, bytes);

    var peFile = new PeFile(buf);


[kernel32.zip](https://github.com/secana/PeNet/files/2841354/kernel32.zip)

**Comment by secana** [comment]
I had a look at the example provided by you. If the last byte is missing, PeNet crashes already in the constructor where the bare minimum of needed structures is parsed. The offset is so small that the data directories and, even more important, the section header cannot be parsed. This makes a mapping of virtual to physical addresses impossible.

Currently I'm out of ideas how to address this issue, except for providing a bigger part of the image in the buffer.

**Comment by drauch** [comment]
To my understanding of the C# language, it would be a big improvement to throw a suitable domain-specific exception like "BeginningOfHeaderUnparsable" or at least a "PeNetParseException". An IndexOutOfRange or an ArgumentException should (almost) never be caught by code because they point out a developer error. This is why throwing such exceptions is not a good idea - the user of your API has no good way to react to them.

We've now decided to write a simple parser for the `IsDLL` flag instead, it most probably would've been overkill to use a full-fledged library just to parse a single flag from a file.
