### ISSUE TITLE
TLS Directory Parsing Doesn't Work

### ISSUE THREAD

**Issue by Akaion** [secana/PeNet#74]
I consistently get a null value for the TLSDirectory of multiple PE images that have valid TLS Directories (confirmed through CFF Explorer & my own PE Parser.)

**Comment by secana** [comment]
Hi @Akaion, would have an example binary for me I can test against?

**Comment by secana** [comment]
Hi @Akaion thx for the example file. I guess I've found and fixed the error. Could try it again with PeNet 1.0.3?

**Comment by Akaion** [comment]
It works correctly now :)
