### ISSUE TITLE
why the  ImageBase type is ulong?

### ISSUE THREAD

**Issue by dmhai** [secana/PeNet#80]
hi , when I debuging a 32bit app(PeNet.Test\Binaries\NetFrameworkConsole.exe)，
why PeFile.ImageNtHeaders.OptionalHeader.ImageBase is a ulong field ,not uint ?

**Comment by secana** [comment]
Hi, you are right that the field in the header is an uint. From the implementation side I use a one class for the x32 and x64 versions of PE files. Because in the x64 version it is a ulong, I just put the x32 bit value in the ulong, too. Hopes that helps.
