### ISSUE TITLE
Debug Directories is not fully dumped

### ISSUE THREAD

**Issue by seanxs** [secana/PeNet#84]
Hi secana,
Sometimes, the debug directory has more than one entry, but PeNet parsers only the first one.
For example,
  Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    AEA44997 cv            22 00002228      E28    Format: RSDS, {A2E56CF0-FB64-CC3D-EABD-4F16EB0AAB11}, 1, csrss.pdb
    AEA44997 coffgrp      1A4 0000224C      E4C    50475500 (PGU)
    AEA44997 repro         24 000023F0      FF0    F0 6C E5 A2 64 FB 3D CC EA BD 4F 16 EB 0A AB 11 56 E5 54 A5 89 68 C0 8A 07 66 50 24 97 49 A4 AE

**Comment by secana** [comment]
Hi @seanxs,
thx for reporting this. Could you provide me a file with the described behavrior for debugging purposes?

**Comment by seanxs** [comment]
Hi secana
the binary file I used is c:\windows\system32\csrss.exe, I can't upload it
Try this command:link.exe /dump /headers c:\windows\system32\csrss.exe, the output will show as previous.
Actually, lots of PE files in the folder and subfolders "c:\windows" have three debug directories.

**Comment by secana** [comment]
Hi @seanxs,
I've released a new version 1.0.8 of PeNet which should fix the issue. If there is anything wrong with it, or you find another bug, feel free to open a new issue :)
