### ISSUE TITLE
PeFile.IsDriver is incorrect

### ISSUE THREAD

**Issue by BrianCatlin** [secana/PeNet#89]
IsDriver is checking if the subsystem is native to determine if an image is a driver or not. This is insufficient. There are native Windows executables (i.e. not linked to a subsystem), such as SMSS.EXE that are user-mode applications. The correct way to determine if an image is a kernel-mode driver is to check if the subsystem is native AND the image is linked against NTOSKRNL.EXE. Windows applications cannot link against NTOSKRNL, and are instead linked against NTDLL.DLL

**Comment by secana** [comment]
Hi @BrianCatlin, would is be enough to check if NTOSKRNL.EXE is present in the imports additionally to the subsystem or is there a better way?

**Comment by BrianCatlin** [comment]
Yes, that should be sufficient

**Comment by secana** [comment]
Fixed in new version.
