### ISSUE TITLE
class ExportFunction needs to support forwarding

### ISSUE THREAD

**Issue by BrianCatlin** [secana/PeNet#90]
In addition to being able to export functions and values from an image, the export directory can forward an export to another image (DLL). This allows more flexibility when re-organizing DLLs, as happened with the great Win32 DLL reorganization that started in Windows 7 and continued to Windows 10. 
Forwarding is achieved by making an RVA in the AddressOfFunctions array point into the section which contains the export directory (data_dir [IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress <= export_rva < data_dir [IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress + data_dir [IMAGE_DIRECTORY_ENTRY_EXPORT].Size), something that normal exports should not do. At that location, there should be a zero terminated ASCII string of form "DLLName.ExportName" for the appropriate place to forward this export to.

The ExportFunction class should have additional properties, such as:
bool has_name;        // !export_name.empty()
bool has_ordinal;     // (ordinal != 0)
bool has_forward;    // !forward_name.empty()
string forward_name;

**Comment by secana** [comment]
Hi @BrianCatlin thanks for the improvement idea. I already implemented it and will release a new version soon.
