### ISSUE TITLE
Q: How to detect that binary contains IL (.NET) code?

### ISSUE THREAD

**Issue by dmitry-lipetsk** [secana/PeNet#92]
Hello,

I want use your library with my storage of binary files.

Could you point me - how I may detect that binary file (DLL, EXE) contains IL code?

Thanks.

**Comment by secana** [comment]
Hi @dmitry-lipetsk. The easiest way to check if a binary is an .NET binary is to check if the COM Descriptor in the Data Directories is set. In that case the `ImageComDescriptor` in `PeFile` would be not `null`.
I hope that helps.

**Comment by dmitry-lipetsk** [comment]
Thanks :)
