### ISSUE TITLE
System.IO.FileNotFoundException: Could not load the specified file.

### ISSUE THREAD

**Issue by neda-kiya** [secana/PeNet#94]
When I try to use PeNet in a Class Library there is an Exception that I couldn't find any solution for it. 

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PeNet, Version=1.0.9.0, Culture=neutral, PublicKeyToken=6cf2bfba59bcfb3f'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---

But when I test PeNet in a Console Program there wasn't any exception ...

**Comment by secana** [comment]
Could not reproduce
