### ISSUE TITLE
VERSIONINFO resource parser

### ISSUE THREAD

**Issue by jdu2600** [secana/PeNet#99]
It would be helpful to have a parser for the VERSIONINFO resource such that these fields can be queried easily (if they exist).

https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource

**Comment by secana** [comment]
I'll start the implementation on that. Shouldn't take too long.

**Comment by secana** [comment]
@jdu2600 I've added the Version info structure to the PeNet version "1.3.0-prerelease". It would be great if you could give me some feedback if it works like you expect it. 
If so, I'll release the official "1.3.0" version.

**Comment by jdu2600** [comment]
That's fantastic - all of the raw data is readily accessible.

Though, for my use case, it would be handy to have quick access to some of the fields rather than having to parse the stringTable looking for the matching key. 

Perhaps something like -
`var peFile = new PeFile("./Binaries/firefox_invalid_x64.exe");
var vsVersionInfo = peFile.Resources.VsVersionInfo;

// helper properties for the 12 predefined string names
Assert.Equal("Firefox", vsVersionInfo.StringFileInfo.szFileDescription);
Assert.Equal("Firefox", vsVersionInfo.StringFileInfo.szProductName);
Assert.Equal(Firefox, vsVersionInfo.StringFileInfo.szInternalName);
Assert.Equal("firefox.exe", vsVersionInfo.StringFileInfo.szOriginalFilename);
Assert.Equal("Mozilla Corporation", vsVersionInfo.StringFileInfo.szCompanyName);
Assert.Equal("\u00a9Firefox and Mozilla Developers; available under the MPL 2 license.", vsVersionInfo.StringFileInfo.szCopyright);
Assert.Equal("Firefox is a Trademark of The Mozilla Foundation.", vsVersionInfo.StringFileInfo.szCopyright);
Assert.Equal("57.0.2", vsVersionInfo.StringFileInfo.szFileVersion);
Assert.Equal("57.0.2", vsVersionInfo.StringFileInfo.szProductVersion);
Assert.Equal(string.Empty, vsVersionInfo.StringFileInfo.szComments);

// string helpers for the two version fields
Assert.Equal("57.0.2.6549", vsVersionInfo.VsFixedFileInfo.szFileVersion);
Assert.Equal("57.0.2.0", vsVersionInfo.VsFixedFileInfo.szProductVersion);`

**Comment by secana** [comment]
That's a good idea. I've build the default string into the "StringTable" structure, as there can be more than one of them, such that putting it into the "StringFileInfo" can be disambiguous. 

Example to access: `Assert.Equal("firefox.exe", vsVersionInfo.StringFileInfo.StringTable[0].OriginalFilename);`

The version containing the direct access to the strings is PeNet 1.3.2
